# Site settings
title: Contact Improv LA
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Contact Improvisation in Los Angeles
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://contactimprovla.github.io" # the base hostname & protocol for your site
github_username:  contactimprovla

# Build settings
markdown: kramdown
